// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rekatjpuqjyafhlvjjsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJla2F0anB1cWp5YWZobHZqanNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTIwMzEsImV4cCI6MjA2NTk4ODAzMX0.ZKhjP1FA5wfxYFs4wSMNALyuru6qYIx4JZG2Y18wavM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);